### ISSUE TITLE
Why is this C++ and not C?

### ISSUE THREAD

**Issue by iboB** [binji/smolnes#3]
I might be missing something, but the only benefit I see of using C++ over C here is that `#include <cstdint>`  is one byte shorter than `#include <stdint.h>`. 

C would compile faster and is (well, at least theoretically) more portable.

**Comment by binji** [comment]
There's a few features of C++ I use:
* `using` is shorter than `typedef`
* A few functions return references instead of pointers
* Some functions use default values
* The result of a ternary is used as a reference
* The precedence of the ternary operator vs. assignment operators is changed in C++, see https://en.cppreference.com/w/cpp/language/operator_precedence#Notes

So I think I could rewrite it as C relatively easily, but it might increase in size a bit.

**Comment by binji** [comment]
I ended up writing it in C here 9f613693f12e41c0cd9df0e5e986951f1e0d3bc0.
